### Loading...

In [1]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns

In [2]:
path = "C:/users/hitesh/Learning/Skillenza/Data/"

In [3]:
filename1 = "HUL_PUR_REG_CONSOLIDATED_JAN2019.xlsb"

### File1

In [4]:
import pandas as pd
from pyxlsb import open_workbook as open_xlsb

df = []

with open_xlsb(path+filename1) as wb:
    with wb.get_sheet(1) as sheet:
        for row in sheet.rows():
            df.append([item.v for item in row])

df = pd.DataFrame(df[1:], columns=df[0])

In [5]:
df.shape

(78770, 7)

In [6]:
df.head()

,None,None,None,None,None,None,None
0,None,None,None,None,None,None,None
1,None,None,None,None,Values,None,None
2,INV Acc Doc number,Vendor PAN Number,Vendor GSTIN/UIN,Document Type,Sum of CGST Amount,Sum of SGST Amount,Sum of IGST Amount
3,5100000001,BKQPS5638P,33BKQPS5638P1Z5,A1,1088.76,1088.76,0
4,5100000002,BKQPS5638P,33BKQPS5638P1Z5,A1,615.5,615.5,0

In [7]:
df.tail()

,None,None,None,None,None,None,None
78765,5100135100,AAFFT6782P,02AAFFT6782P1ZK,RE,8950.5,8950.5,0
78766,5100135200,AAACB7618N,30AAACB7618N1ZP,Y9,0,0,-5047.81
78767,5100135202,AAECA6976A,18AAECA6976A1ZO,RE,5948.9,5948.9,0
78768,5100135203,.,,RE,0,0,253887
78769,Grand Total,None,None,None,5.84782e+08,5.84782e+08,1.4233e+09

In [8]:
rename_col = df.iloc[2].values

In [9]:
df.columns = rename_col

In [10]:
df.head()

,INV Acc Doc number,Vendor PAN Number,Vendor GSTIN/UIN,Document Type,Sum of CGST Amount,Sum of SGST Amount,Sum of IGST Amount
0,None,None,None,None,None,None,None
1,None,None,None,None,Values,None,None
2,INV Acc Doc number,Vendor PAN Number,Vendor GSTIN/UIN,Document Type,Sum of CGST Amount,Sum of SGST Amount,Sum of IGST Amount
3,5100000001,BKQPS5638P,33BKQPS5638P1Z5,A1,1088.76,1088.76,0
4,5100000002,BKQPS5638P,33BKQPS5638P1Z5,A1,615.5,615.5,0

In [11]:
df.drop([0,1,2,78769], inplace= True)

In [12]:
df.reset_index(inplace= True, drop= True )

In [14]:
data = df.copy()

### EDA

In [29]:
data

,INV Acc Doc number,Vendor PAN Number,Vendor GSTIN/UIN,Document Type,Sum of CGST Amount,Sum of SGST Amount,Sum of IGST Amount
0,5100000001,BKQPS5638P,33BKQPS5638P1Z5,A1,1088.76,1088.76,0
1,5100000002,BKQPS5638P,33BKQPS5638P1Z5,A1,615.5,615.5,0
2,5100000003,BKQPS5638P,33BKQPS5638P1Z5,A1,1450.55,1450.55,0
3,5100000004,BKQPS5638P,33BKQPS5638P1Z5,A1,1356.62,1356.62,0
4,5100000005,AEJPA4443E,20AEJPA4443E1Z9,A1,0,0,914.76
5,5100000006,BKQPS5638P,33BKQPS5638P1Z5,A1,0,0,1560.01
6,5100000007,BKQPS5638P,33BKQPS5638P1Z5,A1,0,0,1201.52
7,5100000008,BKQPS5638P,33BKQPS5638P1Z5,A1,1879.86,1879.86,0
8,5100000009,AEJPA4443E,20AEJPA4443E1Z9,A1,0,0,6641.3
9,5100000010,BKQPS5638P,33BKQPS5638P1Z5,A1,0,0,1817.25
10,5100000011,BKQPS5638P,33BKQPS5638P1Z5,A1,445,445,0
11,5100000012,AEJPA4443E,20AEJPA4443E1Z9,A1,0,0,1888.92
12,5100000013,AEJPA4443E,20AEJPA4443E1Z9,A1,0,0,2531.52
13,5100000014,BKQPS5638P,33BKQPS5638P1Z5,A1,251,251,0
14,5100000015,AEJPA4443E,20AEJPA4443E1Z9,A1,0,0,7868.3
15,5100000016,AEJPA4443E,20AEJPA4443E1Z9,A1,0,0,5195.88
16,5100000017,BKQPS5638P,33BKQPS5638P1Z5,A1,876.04,876.04,0
17,5100000018,AEJPA4443E,20AEJPA4443E1Z9,A1,0,0,1410.48
18,5100000019,AEJPA4443E,20AEJPA4443E1Z9,A1,0,0,2343.13
19,5100000020,AABCT3904C,27AABCT3904C1ZR,A1,1661.28,1661.28,0
20,5100000021,AABCT3904C,27AABCT3904C1ZR,A1,3764.01,3764.01,0
21,5100000022,AABCT3904C,27AABCT3904C1ZR,A1,1986.53,1986.53,0
22,5100000023,AABCT3904C,27AABCT3904C1ZR,A1,1474.87,1474.87,0
23,5100000024,AABCT3904C,27AABCT3904C1ZR,A1,0,0,5325.6
24,5100000025,AABCT3904C,27AABCT3904C1ZR,A1,3515.91,3515.91,0
25,5100000026,AABCT3904C,27AABCT3904C1ZR,A1,1889.21,1889.21,0
26,5100000027,AABCT3904C,27AABCT3904C1ZR,A1,1948.13,1948.13,0
27,5100000028,AAFCA7940K,19AAFCA7940K1ZA,A1,0,0,2990.25
28,5100000029,AABCT3904C,27AABCT3904C1ZR,A1,1986.53,1986.53,0
29,5100000030,AAFCA7940K,19AAFCA7940K1ZA,A1,2998,2998,0
...,...,...,...,...,...,...,...
78736,5100135048,AAACK4647E,32AAACK4647E1ZW,RE,3967.56,3967.56,0
78737,5100135049,AAACK4647E,32AAACK4647E1ZW,RE,158.81,158.81,0
78738,5100135050,AAACK4647E,27AAACK4647E1ZN,RE,-4506.64,-4506.64,0
78739,5100135051,AAACK4647E,21AAACK4647E1ZZ,RE,19688.5,19688.5,0
78740,5100135052,AAACK4647E,20AAACK4647E1Z1,RE,714.66,714.66,0
78741,5100135053,AAACK4647E,01AAACK4647E1Z1,RE,189.34,189.34,0
78742,5100135054,AAACK4647E,03AAACK4647E1ZX,RE,6302.19,6302.19,0
78743,5100135055,AAACK4647E,08AAACK4647E1ZN,RE,28548.9,28548.9,0
78744,5100135056,AAACK4647E,08AAACK4647E1ZN,RE,13801.1,13801.1,0
78745,5100135057,AAACK4647E,08AAACK4647E1ZN,RE,248.8,248.8,0
78746,5100135058,AAACK4647E,08AAACK4647E1ZN,RE,25834.1,25834.1,0
78747,5100135059,AAACK4647E,09AAACK4647E1ZL,RE,14718.7,14718.7,0
78748,5100135060,AAACK4647E,10AAACK4647E1Z2,RE,211.04,211.04,0
78749,5100135061,AABFP8593L,33AABFP8593L1ZQ,Y0,3490.75,3490.75,0
78750,5100135062,AAGFM2746K,21AAGFM2746K1ZC,Y0,185.82,185.82,0
78751,5100135063,AAGFM2746K,21AAGFM2746K1ZC,Y0,12718.8,12718.8,0
78752,5100135064,AAEFJ0279J,35AAEFJ0279J1ZA,Y0,21.03,21.03,0
78753,5100135065,AAPFS0731D,24AAPFS0731D1ZH,Y0,3221.63,3221.63,0
78754,5100135066,AAPFS0731D,24AAPFS0731D1ZH,Y0,4528.92,4528.92,0
78755,5100135067,AAHFM4363K,08AAHFM4363K1ZY,Y0,9069.05,9069.05,0
78756,5100135068,AAACD6574B,24AAACD6574B1Z0,Y9,0,0,-28129.5
78757,5100135069,AAACD6574B,24AAACD6574B1Z0,Y9,0,0,-29398.5
78758,5100135070,.,,RE,0,0,3.14005e+06
78759,5100135071,AAXCS3868E,23AAXCS3868E1ZV,Y9,-9534.93,-9534.93,0
78760,5100135072,AABCC2201R,19AABCC2201R1ZM,RE,17670.6,17670.6,0
78761,5100135073,AABCC2201R,19AABCC2201R1ZM,RE,6246.72,6246.72,0
78762,5100135100,AAFFT6782P,02AAFFT6782P1ZK,RE,8950.5,8950.5,0
78763,5100135200,AAACB7618N,30AAACB7618N1ZP,Y9,0,0,-5047.81
78764,5100135202,AAECA6976A,18AAECA6976A1ZO,RE,5948.9,5948.9,0
78765,5100135203,.,,RE,0,0,253887

In [15]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 78766 entries, 0 to 78765
Data columns (total 7 columns):
INV Acc Doc number    78766 non-null object
Vendor PAN Number     78766 non-null object
Vendor GSTIN/UIN      78766 non-null object
Document Type         78766 non-null object
Sum of CGST Amount    78766 non-null object
Sum of SGST Amount    78766 non-null object
Sum of IGST Amount    78766 non-null object
dtypes: object(7)
memory usage: 4.2+ MB

In [18]:
data.isna().sum()

INV Acc Doc number    0
Vendor PAN Number     0
Vendor GSTIN/UIN      0
Document Type         0
Sum of CGST Amount    0
Sum of SGST Amount    0
Sum of IGST Amount    0
dtype: int64

#### Variables

In [24]:
data["INV Acc Doc number"].nunique()

78766

In [25]:
data["Vendor GSTIN/UIN"].nunique()

3887

In [26]:
data["Vendor PAN Number"].nunique()

3672

In [28]:
data["Document Type"].nunique()

5

In [31]:
data[data["Vendor PAN Number"] == ""]

,INV Acc Doc number,Vendor PAN Number,Vendor GSTIN/UIN,Document Type,Sum of CGST Amount,Sum of SGST Amount,Sum of IGST Amount
2566,5100002999,,,RE,0,0,376758
3380,5100003813,,,RE,0,0,224273
3469,5100003902,,,RE,0,0,0
4322,5100006173,,,RE,0,0,8244.81
4339,5100006192,,,RE,0,0,249948
4580,5100006437,,,RE,0,0,45425.3
4616,5100006477,,,RE,0,0,5135.74
4625,5100006486,,,RE,0,0,324334
4705,5100006572,,,RE,0,0,336769
4736,5100006605,,,RE,0,0,5132.96
4861,5100006731,,,RE,0,0,349927
4868,5100006738,,,RE,0,0,412516
4934,5100006805,,,RE,0,0,249948
4956,5100006827,,,RE,0,0,218344
6616,5100008575,,,RE,0,0,339471
7192,5100010969,,,RE,0,0,428864
7203,5100010980,,,RE,0,0,302457
7263,5100011044,,,RE,0,0,268651
7990,5100011784,,,RE,0,0,0
9282,5100013089,,,RE,0,0,0
10215,5100015949,,,RE,0,0,0
10236,5100015971,,,RE,0,0,0
10240,5100015975,,,RE,0,0,0
10242,5100015977,,,RE,0,0,0
10246,5100015981,,,RE,0,0,0
10257,5100015993,,,RE,0,0,0
10270,5100016007,,,RE,0,0,0
10274,5100016011,,,RE,0,0,0
10479,5100016220,,,RE,0,0,0
10556,5100016299,,,RE,0,0,357394
...,...,...,...,...,...,...,...
69544,5100119655,,,RE,0,0,0
69619,5100119738,,,RE,0,0,0
69652,5100119775,,,RE,0,0,0
69703,5100119836,,,RE,0,0,114670
69777,5100119917,,,RE,0,0,14039.2
69843,5100119998,,,RE,0,0,0
69904,5100120070,,,RE,0,0,0
70186,5100120380,,,RE,0,0,0
70194,5100120388,,,RE,0,0,0
70242,5100120440,,,RE,0,0,0
70260,5100120458,,,RE,0,0,0
70264,5100120463,,,RE,0,0,0
70269,5100120468,,,RE,0,0,0
70271,5100120470,,,RE,0,0,0
70299,5100120502,,,RE,0,0,0
70391,5100120605,,,RE,0,0,0
70397,5100120611,,,RE,0,0,0
70408,5100120624,,,RE,0,0,0
70410,5100120627,,,RE,0,0,0
70413,5100120631,,,RE,0,0,0
70463,5100120701,,,RE,0,0,0
70464,5100120702,,,RE,0,0,0
70881,5100121172,,,RE,0,0,75904
72349,5100124525,,,RE,0,0,0
72437,5100124616,,,RE,0,0,0
73374,5100125599,,,RE,0,0,0
73809,5100126052,,,RE,0,0,64177.3
76810,5100130892,,,RE,0,0,0
77116,5100131219,,,RE,0,0,0
77156,5100131306,,,RE,0,0,0